# Generated by Django 4.1.7 on 2024-01-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0002_musiclyric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicLyric',
        ),
    ]
