# Generated by Django 5.0.1 on 2024-01-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0005_billboardlyric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboardlyric',
            name='release_date',
            field=models.FloatField(),
        ),
    ]
