# Generated by Django 5.0.1 on 2024-02-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0007_tracklyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracklyric',
            name='type',
            field=models.CharField(default='music', max_length=255),
        ),
    ]
