# Generated by Django 5.0.1 on 2024-02-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0010_newspotifylyric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewSpotifyLyric',
            new_name='SpotifyMusicLyric',
        ),
    ]
