# Generated by Django 5.0.1 on 2024-03-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0011_rename_newspotifylyric_spotifymusiclyric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillBoardLyric',
        ),
        migrations.DeleteModel(
            name='TrackLyric',
        ),
    ]
