# Generated by Django 4.1.7 on 2023-12-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='search_id',
        ),
    ]
