# Generated by Django 4.1.7 on 2023-12-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_searchhistory_search_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_type',
            field=models.CharField(choices=[('movie', 'movie'), ('plot', 'plot'), ('music', 'music')], default=None, max_length=20),
        ),
    ]
