# Generated by Django 4.1.7 on 2023-12-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0003_moviesearchhistory_user_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesearchhistory',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
