# Generated by Django 4.1.7 on 2023-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_moviesearchhistory_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSynopsis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('plot_synopsis', models.TextField()),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
    ]
