# Generated by Django 4.1.7 on 2024-01-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_moviesynopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255)),
                ('movie', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='movie_quote')),
            ],
        ),
    ]
