# Generated by Django 4.1.7 on 2024-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
