# Generated by Django 4.1.7 on 2024-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_alter_quote_poster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='poster_image',
        ),
        migrations.AddField(
            model_name='quote',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
