# Generated by Django 4.1.7 on 2024-01-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0010_delete_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255)),
                ('movie', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('poster_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
