# Generated by Django 5.0.1 on 2024-01-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0012_moviequoteoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviequoteoverview',
            name='movie',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
