# Generated by Django 5.0.1 on 2024-01-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0013_moviequoteoverview_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviequoteoverview',
            name='imdb_rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moviequoteoverview',
            name='metascore',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
