# Generated by Django 5.0.1 on 2024-01-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0014_alter_moviequoteoverview_imdb_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieQuoteOverview',
        ),
    ]
