# Generated by Django 5.0.1 on 2024-01-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0015_delete_moviequoteoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieQuoteOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=255)),
                ('movie', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('poster_link', models.URLField(blank=True, null=True)),
                ('genre', models.CharField(max_length=255)),
                ('imdb_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('metascore', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
